export { Sparse }                                                                from './src/Sparse'
export { transpose }                                                             from './src/infrastructure/algebra'
export { indexed, indexedTo, indexedBy, indexedOf }                              from './src/infrastructure/indexed'
export { Stat }                                                                  from './src/Stat'
export { IntoList, IntoAverage, IntoSum, IntoMax, IntoMin, IntoFirst, IntoLast } from './src/intos'